name: "🐛 Bug Report"
description: Report a bug in ProtegeDesk
title: "[BUG] "
labels: ["type: bug", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots or videos to help explain the problem.
      placeholder: Drag and drop images/videos here...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - UI/Layout
        - Axiom Editor
        - Graph Visualization
        - Reasoner
        - AI Co-pilot
        - Import/Export
        - State Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Major feature broken
        - Medium - Feature works but with issues
        - Low - Minor cosmetic issue
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of ProtegeDesk are you using?
      placeholder: "e.g., 0.2.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      placeholder: "e.g., Chrome 120"
    validations:
      required: false

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: If applicable, paste any error messages from the browser console (F12 → Console).
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other relevant information about the problem.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported.
          required: true
        - label: I have tried clearing my browser cache and refreshing.
          required: false

